# Generated by Django 5.0.4 on 2026-06-15 06:33

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablet_app', '0001_initial'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('badge_icon', models.CharField(max_length=50)),
                ('criteria_type', models.CharField(choices=[('consistency', 'Consistency Days'), ('test_count', 'Tests Completed'), ('improvement', 'Score Improvement'), ('study_time', 'Study Hours')], max_length=50)),
                ('criteria_value', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
            },
        ),
        migrations.CreateModel(
            name='RewardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('reward_type', models.CharField(choices=[('digital', 'Digital Reward'), ('activity', 'Activity Reward'), ('privilege', 'Privilege Reward'), ('praise', 'Praise Reward')], max_length=50)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('min_score', models.FloatField(default=0, help_text='Min avg score% to suggest this reward')),
                ('max_score', models.FloatField(default=100, help_text='Max avg score% to suggest this reward')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='studentmodel',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='student_id',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='rolemodel',
            name='type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Parent', 'Parent'), ('Employee', 'Employee'), ('Customer', 'Customer')], max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='parent',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='mobile_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='BadgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('badge_type', models.CharField(choices=[('performance', 'Performance'), ('consistency', 'Consistency'), ('improvement', 'Improvement'), ('completion', 'Completion'), ('speed', 'Speed'), ('subject', 'Subject')], max_length=50)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('threshold', models.FloatField(help_text='Value needed to earn this badge (score%, streak days, etc)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(blank=True, help_text='If subject-specific badge', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablet_app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard', models.IntegerField(help_text='Class standard (1-12)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('section', models.CharField(blank=True, help_text='Section name like A, B, C (optional)', max_length=10, null=True)),
                ('academic_year', models.CharField(default='2024-25', help_text='Academic year like 2024-25', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'unique_together': {('standard', 'section', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='BatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('timing', models.CharField(blank=True, max_length=50, null=True)),
                ('days', models.JSONField(default=list)),
                ('student_class', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('students', models.ManyToManyField(blank=True, related_name='batches', to='user_management.studentmodel')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablet_app.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to=settings.AUTH_USER_MODEL)),
                ('class_ref', models.ForeignKey(blank=True, help_text='Which class this batch belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='user_management.classmodel')),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
            },
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='user_management.classmodel'),
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei_number', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='device_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_management.devicemodel'),
        ),
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('due_date', models.DateTimeField()),
                ('total_marks', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ManyToManyField(blank=True, related_name='assigned_homework', to='user_management.studentmodel')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homework', to='user_management.batchmodel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_homework', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_homework', to='tablet_app.studentgroupmodel')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablet_app.subject')),
            ],
            options={
                'verbose_name': 'Homework',
                'verbose_name_plural': 'Homework',
            },
        ),
        migrations.CreateModel(
            name='LearningStyleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('visual', 'Visual Learner'), ('reading', 'Reading Learner'), ('practice', 'Practice Learner'), ('mixed', 'Mixed Learner')], default='mixed', max_length=50)),
                ('visual_score', models.FloatField(default=0)),
                ('reading_score', models.FloatField(default=0)),
                ('practice_score', models.FloatField(default=0)),
                ('confidence', models.FloatField(default=0)),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('data_points', models.IntegerField(default=0)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_style', to='user_management.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationPreferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homework_assigned', models.BooleanField(default=True)),
                ('homework_due', models.BooleanField(default=True)),
                ('homework_graded', models.BooleanField(default=True)),
                ('test_scheduled', models.BooleanField(default=True)),
                ('test_result', models.BooleanField(default=True)),
                ('goal_achieved', models.BooleanField(default=True)),
                ('badge_earned', models.BooleanField(default=True)),
                ('weekly_report', models.BooleanField(default=True)),
                ('teacher_remark', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to='user_management.studentmodel')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='StudentGoalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_type', models.CharField(choices=[('score', 'Score Target'), ('consistency', 'Consistency'), ('study_time', 'Study Time'), ('improvement', 'Improvement')], max_length=20)),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField(default=0)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_achieved', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goals', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='user_management.studentmodel')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablet_app.subject')),
            ],
            options={
                'verbose_name': 'Student Goal',
                'verbose_name_plural': 'Student Goals',
            },
        ),
        migrations.CreateModel(
            name='StudentRewardModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('given_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_rewards', to=settings.AUTH_USER_MODEL)),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_to', to='user_management.rewardmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='user_management.studentmodel')),
            ],
        ),
        migrations.CreateModel(
            name='TabletLeadModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_type', models.CharField(choices=[('Student', 'Student'), ('School', 'School'), ('College', 'College'), ('Institute', 'Institute'), ('Individual', 'Individual')], max_length=30)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('tablet_model', models.CharField(max_length=100)),
                ('tablet_variant', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_per_unit', models.FloatField(blank=True, null=True)),
                ('total_price', models.FloatField(blank=True, null=True)),
                ('demo_required', models.BooleanField(default=False)),
                ('demo_done', models.BooleanField(default=False)),
                ('demo_date', models.DateField(blank=True, null=True)),
                ('stage', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Demo Scheduled', 'Demo Scheduled'), ('Demo Done', 'Demo Done'), ('Negotiation', 'Negotiation'), ('Order Confirmed', 'Order Confirmed'), ('Delivered', 'Delivered'), ('Lost', 'Lost')], default='New', max_length=50)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Pending', max_length=20)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tablet_leads_assigned', to='user_management.employeemodel')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tablet_leads_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TabletLeadFollowUpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_type', models.CharField(choices=[('Call', 'Call'), ('Whatsapp', 'WhatsApp'), ('Demo', 'Demo'), ('Meeting', 'Meeting'), ('Payment', 'Payment Follow-Up'), ('Delivery', 'Delivery Follow-Up'), ('Support', 'Support')], max_length=30)),
                ('followup_date', models.DateTimeField(help_text='Next follow-up date & time')),
                ('comment', models.TextField()),
                ('stage_update', models.CharField(blank=True, choices=[('Contacted', 'Contacted'), ('Demo Scheduled', 'Demo Scheduled'), ('Demo Done', 'Demo Done'), ('Negotiation', 'Negotiation'), ('Order Confirmed', 'Order Confirmed'), ('Delivered', 'Delivered'), ('Lost', 'Lost')], help_text='Update lead stage after this follow-up', max_length=50, null=True)),
                ('next_followup_date', models.DateTimeField(blank=True, help_text='If another follow-up is required', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('followup_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tablet_followups', to=settings.AUTH_USER_MODEL)),
                ('tablet_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='user_management.tabletleadmodel')),
            ],
            options={
                'verbose_name': 'Tablet Lead Follow-Up',
                'verbose_name_plural': 'Tablet Lead Follow-Ups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherRemarkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remark', models.TextField()),
                ('remark_type', models.CharField(choices=[('general', 'General'), ('concern', 'Concern'), ('appreciation', 'Appreciation')], default='general', max_length=20)),
                ('is_visible_to_parent', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_remarks', to='user_management.studentmodel')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_remarks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Remark',
                'verbose_name_plural': 'Teacher Remarks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imei_number', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.vendormodel')),
            ],
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='parent',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HomeworkSubmissionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_minutes', models.IntegerField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='user_management.homeworkmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='user_management.studentmodel')),
            ],
            options={
                'verbose_name': 'Homework Submission',
                'verbose_name_plural': 'Homework Submissions',
                'unique_together': {('homework', 'student')},
            },
        ),
        migrations.CreateModel(
            name='StudentAchievementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.achievementmodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='user_management.studentmodel')),
            ],
            options={
                'verbose_name': 'Student Achievement',
                'verbose_name_plural': 'Student Achievements',
                'unique_together': {('student', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='StudentBadgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.JSONField(blank=True, help_text='Extra info like test_id, score, streak_count', null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_by', to='user_management.badgemodel')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='user_management.studentmodel')),
            ],
            options={
                'unique_together': {('student', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='TeacherAssignmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_role', models.CharField(choices=[('subject_teacher', 'Subject Teacher'), ('class_teacher', 'Class Teacher'), ('principal', 'Principal/Admin')], default='subject_teacher', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_classes', models.ManyToManyField(help_text='Classes this teacher teaches (e.g., 8A, 8B, 9A)', related_name='assigned_teachers', to='user_management.classmodel')),
                ('assigned_subjects', models.ManyToManyField(help_text='Subjects this teacher can teach (e.g., Math, Science)', related_name='assigned_teachers', to='tablet_app.subject')),
                ('homeroom_class', models.ForeignKey(blank=True, help_text='If class teacher, which class is their homeroom', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_teacher', to='user_management.classmodel')),
                ('teacher', models.ForeignKey(limit_choices_to={'role__type': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Assignment',
                'verbose_name_plural': 'Teacher Assignments',
                'unique_together': {('teacher',)},
            },
        ),
    ]
