# Generated by Django 5.0.4 on 2026-06-17 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_achievementmodel_rewardmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolemodel',
            name='type',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Teacher', 'Teacher'), ('Parent', 'Parent'), ('Employee', 'Employee'), ('Customer', 'Customer'), ('Coordinator', 'Coordinator')], max_length=100, null=True),
        ),
    ]
