# Generated by Django 5.0.4 on 2026-06-17 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_alter_rolemodel_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
