# Generated by Django 5.0.4 on 2026-06-19 14:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0004_addressmodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringDataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('coordinator', 'Coordinator'), ('class', 'Class'), ('school', 'School')], max_length=20)),
                ('entity_id', models.IntegerField()),
                ('score', models.FloatField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scoring Data',
                'unique_together': {('entity_type', 'entity_id')},
            },
        ),
        migrations.CreateModel(
            name='CoordinatorTeacherMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_classes', models.ManyToManyField(related_name='coordinator_managed_classes', to='user_management.classmodel')),
                ('coordinator', models.ForeignKey(limit_choices_to={'role__type': 'Coordinator'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_teachers', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(limit_choices_to={'role__type': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_by_coordinator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coordinator Teacher Mapping',
                'unique_together': {('coordinator', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='PrincipalCoordinatorMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(limit_choices_to={'role__type': 'Coordinator'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_by_principal', to=settings.AUTH_USER_MODEL)),
                ('principal', models.ForeignKey(limit_choices_to={'role__type': 'Customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_coordinators', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Principal Coordinator Mapping',
                'unique_together': {('principal', 'coordinator')},
            },
        ),
    ]
