# Generated by Django 5.0.4 on 2026-06-30 13:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablet_app', '0003_studysession_offline_usage_studysession_pdfs_opened_and_more'),
        ('user_management', '0005_scoringdatamodel_coordinatorteachermapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('board', models.CharField(choices=[('GSEB', 'GSEB'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('Other', 'Other')], max_length=50)),
                ('medium', models.CharField(choices=[('Gujarati', 'Gujarati'), ('Hindi', 'Hindi'), ('English', 'English'), ('Other', 'Other')], max_length=50)),
                ('principal_name', models.CharField(max_length=150)),
                ('principal_phone', models.CharField(max_length=15)),
                ('principal_email', models.EmailField(max_length=254)),
                ('total_tablets_given', models.IntegerField(default=0)),
                ('working_days', models.IntegerField(default=220)),
                ('timetable_structure', models.JSONField(blank=True, null=True)),
                ('exam_test_structure', models.JSONField(blank=True, null=True)),
                ('academic_year', models.CharField(default='2024-25', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='classmodel',
            name='classname',
            field=models.CharField(default='Class A', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classmodel',
            name='room',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='classmodel',
            name='subject',
            field=models.CharField(default='Maths', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classmodel',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__type': 'Teacher'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='activation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='battery_health',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='device_status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='tablet_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='warranty_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teacherassignmentmodel',
            name='school_principal',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__type': 'Customer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_teacher_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classmodel',
            name='standard',
            field=models.IntegerField(blank=True, help_text='Class standard (1-12)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.CreateModel(
            name='CoordinatorActionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('issue', models.TextField()),
                ('responsible', models.CharField(max_length=200)),
                ('required_action', models.TextField()),
                ('status', models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Discussed', 'Discussed'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Escalated', 'Escalated to Principal'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CoordinatorEscalationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management.studentmodel')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations_against', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coordinator Escalation',
                'verbose_name_plural': 'Coordinator Escalations',
            },
        ),
        migrations.CreateModel(
            name='CoordinatorAssignmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_management.classmodel')),
                ('coordinator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_assignments', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tablet_app.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_coordinator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('coordinator', 'class_obj', 'teacher')},
            },
        ),
    ]
