# Generated by Django 5.0.4 on 2026-07-07 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_alter_devicemodel_user_deviceqrcodemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='classmodel',
            name='school_principal',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__type': 'Customer'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_school_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
