# Generated by Django 5.0.4 on 2026-06-15 06:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tablet_app', '0001_initial'),
        ('user_management', '0002_achievementmodel_rewardmodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='studentgroupmodel',
            name='class_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_groups', to='user_management.classmodel'),
        ),
        migrations.AddField(
            model_name='studentgroupmodel',
            name='created_by',
            field=models.ForeignKey(limit_choices_to={'role__type': 'Teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_student_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentgroupmodel',
            name='students',
            field=models.ManyToManyField(related_name='groups', to='user_management.studentmodel'),
        ),
        migrations.AddField(
            model_name='studenttestattemptmodel',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='user_management.studentmodel'),
        ),
        migrations.AddField(
            model_name='studentanswermodel',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tablet_app.studenttestattemptmodel'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.studentmodel'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablet_app.subject'),
        ),
        migrations.AddField(
            model_name='studentgroupmodel',
            name='subject',
            field=models.ForeignKey(blank=True, help_text="If subject-specific group like 'Weak in Algebra'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablet_app.subject'),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='pdf',
            field=models.ManyToManyField(related_name='test', to='tablet_app.pdflibrarymodel'),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='tests', to='user_management.studentmodel'),
        ),
        migrations.AddField(
            model_name='testmodel',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tablet_app.subject'),
        ),
        migrations.AddField(
            model_name='studenttestattemptmodel',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testattempt', to='tablet_app.testmodel'),
        ),
        migrations.AddField(
            model_name='questionsmodel',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tablet_app.testmodel'),
        ),
    ]
