# Generated by Django 5.0.4 on 2026-06-30 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tablet_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='offline_usage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studysession',
            name='pdfs_opened',
            field=models.ManyToManyField(blank=True, to='tablet_app.pdflibrarymodel'),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='tablet_app.subject')),
            ],
        ),
        migrations.AddField(
            model_name='studysession',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tablet_app.chapter'),
        ),
    ]
